# Generated by Django 6.0.5 on 2026-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='geoFencingRadius',
            field=models.IntegerField(default=500),
        ),
    ]
