# Generated by Django 6.0.5 on 2026-06-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_posalert_posterminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
