# Generated by Django 6.0.5 on 2026-06-15 11:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('productId', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
