# Generated by Django 6.0.5 on 2026-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_category_organization_location_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brochure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='vendorId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
