# Generated by Django 6.0.5 on 2026-06-04 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_project_projecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('time_taken_mins', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employmentType',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=50),
        ),
    ]
