# Generated by Django 6.0.5 on 2026-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_organization_department_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('departmentCode', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('roleCode', 'organization')},
        ),
    ]
