# Generated by Django 6.0.5 on 2026-06-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_department_departmentcode_alter_role_rolecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='defaultDashboard',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
