# Generated by Django 6.0.5 on 2026-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_role_defaultdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('employeeId', 'organization')},
        ),
    ]
