# Generated by Django 6.0.5 on 2026-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_department_departmentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentCode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
