# Generated by Django 6.0.5 on 2026-06-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee_accessiblesites_alter_employee_siteid'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='visibleKpis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
