# Generated by Django 6.0.5 on 2026-06-13 18:45

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_role_visiblekpis'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='contactEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('assignedSalesExecutiveId', models.CharField(blank=True, max_length=50, null=True)),
                ('coverageArea', models.CharField(blank=True, max_length=200, null=True)),
                ('geoFencing', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
    ]
