# Generated by Django 6.0.5 on 2026-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_site_contactemail_site_contactphone_site_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
