# Generated by Django 6.0.5 on 2026-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='activateDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='contactName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='modulesEnabled',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='site',
            name='productType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='siteCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
