# Generated by Django 6.0.5 on 2026-06-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_site_activatedate_site_contactname_site_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
