# Generated by Django 6.0.5 on 2026-06-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='relatedDistributorId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
