# Generated by Django 6.0.5 on 2026-07-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_organization_billingterm_organization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dailyAllowance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='perKmRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='employee',
            name='vehicleType',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('None', 'None')], default='None', max_length=50),
        ),
    ]
