# Generated by Django 6.0.5 on 2026-06-04 17:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0008_message_readby'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=50)),
                ('employeeName', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('photo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
