# Generated by Django 6.0.5 on 2026-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_travelexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingentry',
            name='plannedRouteSummary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
