# Generated by Django 6.0.5 on 2026-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_trackingentry_plannedroutesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingentry',
            name='clientVisits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trackingentry',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
