# Generated by Django 6.0.5 on 2026-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_trackingentry_clientvisits_trackingentry_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingentry',
            name='status',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('idle', 'idle'), ('completed', 'completed')], max_length=50),
        ),
    ]
