# Generated by Django 6.0.5 on 2026-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_alter_trackingentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingentry',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
