# Generated by Django 6.0.5 on 2026-06-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0013_trackingentry_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='expenseStatus',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='foodExpense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='fuelExpense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='proofUrl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='taskType',
            field=models.CharField(default='Visit', max_length=50),
        ),
    ]
