# Generated by Django 6.0.5 on 2026-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0014_employeetask_distance_employeetask_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('low_achievement', 'low_achievement'), ('inactive_gps', 'inactive_gps'), ('pending_approval', 'pending_approval'), ('compliance', 'compliance'), ('license_expiry', 'license_expiry'), ('stock_low', 'stock_low'), ('tracking_update', 'tracking_update'), ('new_order', 'new_order'), ('travel_start', 'travel_start'), ('expense_approval', 'expense_approval'), ('new_employee', 'new_employee')], max_length=50),
        ),
    ]
