# Generated by Django 6.0.5 on 2026-07-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='checkInLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkInLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkInPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkOutLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkOutLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='checkOutPhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
