# Generated by Django 6.0.5 on 2026-07-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_attendanceentry_checkinlocationlat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingentry',
            name='checkInPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingentry',
            name='checkOutPhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
