# Generated by Django 6.0.5 on 2026-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0017_trackingentry_checkinphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='actualEndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='actualStartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('in-progress', 'in-progress'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled')], default='scheduled', max_length=50),
        ),
    ]
