# Generated by Django 6.0.5 on 2026-07-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_meeting_actualendtime_meeting_actualstarttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endLocationName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='momData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startLocationName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
