# Generated by Django 6.0.5 on 2026-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_meeting_endlocationname_meeting_momdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
