# Generated by Django 6.0.5 on 2026-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_meeting_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancelReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
