# Generated by Django 6.0.5 on 2026-07-18 14:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_meeting_cancelreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularizationRequest',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=200)),
                ('employeeId', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('requestedTime', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
