# Generated by Django 6.0.5 on 2026-07-20 08:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_regularizationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleConfig',
            fields=[
                ('id', models.CharField(default=core.models.generate_uuid, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('ratePerKm', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='cancelReason',
        ),
    ]
