# Generated by Django 6.0.5 on 2026-07-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_vehicleconfig_remove_meeting_cancelreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='vehicleRate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
