# Generated by Django 6.0.5 on 2026-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0024_meeting_vehiclerate_meeting_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endMeterPhoto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startMeterPhoto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
