# Generated by Django 6.0.5 on 2026-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0025_meeting_endmeterphoto_meeting_startmeterphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='calculatedDistanceKms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endMeterLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endMeterLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='endMeterLocationName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startMeterLocationLat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startMeterLocationLng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startMeterLocationName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
