# Generated by Django 6.0.5 on 2026-07-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0026_meeting_calculateddistancekms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endMeterTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='startMeterTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
