# Generated by Django 6.0.5 on 2026-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0027_meeting_endmetertime_meeting_startmetertime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('internal', 'internal'), ('client', 'client'), ('sales', 'sales'), ('follow-up', 'follow-up'), ('demo', 'demo'), ('audit', 'audit')], max_length=50),
        ),
    ]
